language: node_js
node_js:
  - 10
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add ./deploy-key
  - yarn build
  - ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com 'cd prod; rm -rf *; pm2 stop all;'
  - scp -R build root@jcontchem.com:/root/prod
  - ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com 'cd prod; pm2 serve;'
