language: node_js
node_js:
  - 10
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_2300fe280467_key -iv $encrypted_2300fe280467_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
jobs:
  include:
    - stage: test and build
      script: npm run build
after_success:
  # Setup SSH key
  - eval "$(ssh-agent -s)"
  - chmod 600 deploykey
  - ssh-add ./deploykey
  # Build
  - npm run build
  # Cleanup server
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'pm2 delete all;
    cd prod;
    rm -rf *;'
  # Replace recap secret placeholder with proper key
  - sed -i "s/REPLACE_ME_WITH_RECAPTHCA_SECRET/$(cat recaptchasecret)/g" server/index.js
  # Upload repo, serve build and server
  - scp -i ./deploykey -o StrictHostKeyChecking=no -r server build root@jcontchem.com:/root/prod
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'cd prod;
    pm2 serve build --port=80 --spa --name=frontend;
    cd server;
    npm init -y;
    npm install express;
    pm2 start index.js --name=api'
