language: node_js
node_js:
 - 10
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add ./deploy-key
  - ssh root@jcontchem.com
  - cd prod
  - git pull
  - yarn build
  - cd build
  - pm2 serve