language: node_js
node_js:
  - 10
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add ./deploy-key
  - ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com << EOF
  cd prod;
  git pull;
  yarn build;
  cd build
  pm2 serve
EOF
