language: node_js
node_js:
  - 10
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_2300fe280467_key -iv $encrypted_2300fe280467_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
jobs:
  include:
    - stage: test and build
      script: npm run build
after_success:
  # Setup SSH key
  - eval "$(ssh-agent -s)"
  - chmod 600 deploykey
  - ssh-add ./deploykey
  # Build
  - npm run build
  # Clean
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'pm2 stop all; cd prod; rm -rf *;'
  # Replace recap secret placeholder with proper key
  - sed 's/REPLACE_ME_WITH_RECAPTCHA_SECRET/$(cat recaptchasecret)/g' server/index.js
  # Upload repo, serve build and server
  - ls
  # - scp -i ./deploykey -o StrictHostKeyChecking=no -r ./* root@jcontchem.com:/root/prod
  # - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
  #   'cd prod; npm install; cd build; pm2 serve --port=80 --spa; cd ../server; pm2 serve --port=5000'
