language: node_js
node_js:
  - 10
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_2300fe280467_key -iv $encrypted_2300fe280467_iv
    -in deploykey.enc -out deploykey -d
  - openssl aes-256-cbc -K $encrypted_2300fe280467_key -iv $encrypted_2300fe280467_iv -in recaptchasecret.enc -out recaptchasecret -d
jobs:
  include:
    - stage: test and build
      script: npm run build
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploykey
  - ssh-add ./deploykey
  - npm run build
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'pm2 stop all; cd prod; rm -rf *; cd ../api; rm -rf *'
  - scp -i ./deploykey -o StrictHostKeyChecking=no -r build root@jcontchem.com:/root/prod
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'cd prod/build; pm2 serve --port=80 --spa;'
  - sed "s/REPLACE_ME_WITH_RECAPTCHA_SECRET/$(cat recaptchasecret)" server/server.ts
  - scp -i ./deploykey -o StrictHostKeyChecking=no server/index.js root@jcontchem.com:/root/prod
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'cd api; pm2 serve index.js --port=5000;'
