language: node_js
node_js:
  - 10
branches:
  only:
    - master
jobs:
  - include:
      - stage: Tests and Build
        script: npm run test
      - script: npm run build
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploykey
  - ssh-add ./deploykey
  - npm run build
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'cd prod; rm -rf *; pm2 stop all;'
  - scp -i ./deploykey -o StrictHostKeyChecking=no -r build root@jcontchem.com:/root/prod
  - ssh -i ./deploykey -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@jcontchem.com
    'cd prod/build; pm2 serve --port=80 --spa;'
before_install:
  - openssl aes-256-cbc -K $encrypted_2300fe280467_key -iv $encrypted_2300fe280467_iv
    -in deploykey.enc -out deploykey -d
